export const DATABASE_STATS_REFRESH = 'DATABASE_STATS_REFRESH';
export const DATABASE_STATS_RECEIVE = 'DATABASE_STATS_RECEIVE';
export const COLLECTION_CLEAR_INTENT = 'COLLECTION_CLEAR_INTENT';
export const COLLECTION_CLEAR_RECEIVE = 'COLLECTION_CLEAR_RECEIVE';
export const URI_POLICY_CHANGE = 'URI_POLICY_CHANGE';
